run:
  allow-parallel-runners: true

linters:
  enable-all: true
  disable:
    - varnamelen
    - nonamedreturns
    - exhaustivestruct
    - gofumpt
    - gci

issues:
  max-issues-per-linter: 0
  max-same-issues: 0